apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ftezedor/myapp:v1  # Your Docker image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000  # App port
        env:
        - name: NODE_ENV
          value: "production"
        # Add more environment variables if needed


